version: "3"

services:
  web:
    build:
      context: .
      args:
        REQUIREMENTS: local.txt
    #command: sleep infinity
    env_file:
      - .env
    volumes:
      - .:/project
    ports:
      - ${WEB_PORT:-8000}:8000